#!/bin/bash
# =============================================================================
# zapret2 entrypoint — изолированный режим
#
# Вся работа с iptables происходит ВНУТРИ сетевого namespace контейнера.
# Хостовая сеть не затрагивается.
#
# Поток трафика:
#   Клиент → SOCKS5 (Dante, порт 1080)
#           → Dante создаёт соединение от имени пользователя proxyuser
#           → iptables внутри контейнера: трафик proxyuser → NFQUEUE 200
#           → nfqws2 применяет DPI-обход (Lua стратегии)
#           → пакет уходит наружу через eth0 контейнера
# =============================================================================

set -euo pipefail

# ── Цвета ─────────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
MAGENTA='\033[0;35m'
BLUE='\033[0;34m'
NC='\033[0m'

ts()        { date '+%Y-%m-%d %H:%M:%S'; }
log_info()  { echo -e "${GREEN}[$(ts)] [INFO]${NC}  $*"; }
log_debug() { [[ "${LOG_LEVEL:-info}" == "debug" ]] && echo -e "${CYAN}[$(ts)] [DEBUG]${NC} $*" || true; }
log_warn()  { echo -e "${YELLOW}[$(ts)] [WARN]${NC}  $*"; }
log_error() { echo -e "${RED}[$(ts)] [ERROR]${NC} $*" >&2; }

# ── Конфиг ────────────────────────────────────────────────────────────────────
SOCKS5_PORT="${SOCKS5_PORT:-1080}"
NFQUEUE_NUM="${NFQUEUE_NUM:-200}"
ZAPRET_CONFIG="${ZAPRET_CONFIG:-/opt/zapret2/config}"
LOG_LEVEL="${LOG_LEVEL:-info}"

# Загружаем пользовательский конфиг если есть
if [[ -f "$ZAPRET_CONFIG" ]]; then
    log_info "Loading config: $ZAPRET_CONFIG"
    # shellcheck disable=SC1090
    source "$ZAPRET_CONFIG"
else
    log_warn "Config not found ($ZAPRET_CONFIG), using defaults"
fi

# ── Проверка capabilities ──────────────────────────────────────────────────────
check_caps() {
    if ! iptables -t mangle -L OUTPUT -n &>/dev/null; then
        log_error "NET_ADMIN capability required!"
        log_error "Add: --cap-add NET_ADMIN --cap-add NET_RAW"
        exit 1
    fi
    log_info "Capabilities OK"
}

# ── Пользователь proxyuser ─────────────────────────────────────────────────────
ensure_proxyuser() {
    if ! id proxyuser &>/dev/null; then
        adduser -D -H -s /bin/false proxyuser
        log_info "Created user: proxyuser"
    fi
}

# ── iptables: только внутри namespace контейнера ───────────────────────────────
setup_iptables() {
    log_info "Configuring iptables (container-local only)"

    # Очистить предыдущие правила
    iptables -t mangle -F OUTPUT 2>/dev/null || true

    # 1. Loopback — пропустить
    iptables -t mangle -A OUTPUT -o lo -j RETURN

    # 2. Локальные сети — пропустить (не обходить DPI для локального)
    iptables -t mangle -A OUTPUT -d 10.0.0.0/8      -j RETURN
    iptables -t mangle -A OUTPUT -d 172.16.0.0/12   -j RETURN
    iptables -t mangle -A OUTPUT -d 192.168.0.0/16  -j RETURN

    # 3. DNS — пропустить (не ломать резолвинг)
    iptables -t mangle -A OUTPUT -p udp --dport 53   -j RETURN
    iptables -t mangle -A OUTPUT -p tcp --dport 53   -j RETURN

    # 4. root трафик — пропустить (включая сам nfqws2, иначе loop)
    iptables -t mangle -A OUTPUT -m owner --uid-owner root -j RETURN

    # 5. ТОЛЬКО трафик proxyuser идёт через NFQUEUE → nfqws2
    iptables -t mangle -A OUTPUT \
        -m owner --uid-owner proxyuser \
        -p tcp \
        -j NFQUEUE --queue-num "$NFQUEUE_NUM" --queue-bypass

    log_info "iptables rules applied"

    if [[ "${LOG_LEVEL}" == "debug" ]]; then
        log_debug "Current mangle OUTPUT chain:"
        iptables -t mangle -L OUTPUT -v -n
    fi
}

# ── Dante SOCKS5 конфиг ────────────────────────────────────────────────────────
write_sockd_conf() {
    # Берём IP контейнера (не хардкодим eth0 — может быть другой интерфейс)
    local ext_ip
    ext_ip=$(ip -4 route get 1.1.1.1 2>/dev/null | awk '/src/{for(i=1;i<=NF;i++) if($i=="src") print $(i+1)}' | head -1)

    if [[ -z "$ext_ip" ]]; then
        # Fallback: первый не-loopback IP
        ext_ip=$(ip -4 addr show | awk '/inet /{gsub(/\/.*/, "", $2); print $2}' | grep -v '^127\.' | head -1)
    fi

    log_info "External IP for Dante: $ext_ip"

    cat > /etc/sockd.conf <<EOF
# Dante SOCKS5 — auto-generated by entrypoint.sh
logoutput: stderr

internal: 0.0.0.0 port = ${SOCKS5_PORT}
external: ${ext_ip}

# Без аутентификации (добавь userauth при необходимости)
clientmethod: none
socksmethod: none

user.privileged:   root
user.unprivileged: proxyuser

# Разрешить всем подключаться
client pass {
    from: 0.0.0.0/0 to: 0.0.0.0/0
    log: error
}

# Разрешить всё проксировать
socks pass {
    from: 0.0.0.0/0 to: 0.0.0.0/0
    log: error connect disconnect
}
EOF
    log_info "sockd.conf written"
}

# ── Сборка аргументов nfqws2 ───────────────────────────────────────────────────
build_nfqws_args() {
    NFQWS_ARGS=(
        "--qnum=${NFQUEUE_NUM}"
        "--lua-init=@/opt/zapret2/lua/zapret-lib.lua"
        "--lua-init=@/opt/zapret2/lua/zapret-antidpi.lua"
    )

    if [[ "${NFQWS2_ENABLE:-0}" == "1" ]] && [[ -n "${NFQWS2_OPT:-}" ]]; then
        log_info "Strategy: custom (NFQWS2_OPT)"
        # Разбиваем строку опций в массив безопасно
        read -ra _extra <<< "$NFQWS2_OPT"
        NFQWS_ARGS+=("${_extra[@]}")
    else
        log_info "Strategy: default (multidisorder)"
        NFQWS_ARGS+=(
            "--filter-tcp=80,443"
            "--filter-l7=http,tls"
            "--lua-desync=multidisorder:pos=midsld"
        )
    fi

    log_debug "nfqws2 args: ${NFQWS_ARGS[*]}"
}

# ── Логирование вывода процессов ───────────────────────────────────────────────
process_nfqws_log() {
    local line="$1"
    if echo "$line" | grep -qE "(desync|fake|split|disorder|wssize|seqovl)"; then
        echo -e "${MAGENTA}[$(ts)] [DPI]${NC} ${YELLOW}${line}${NC}"
    elif echo "$line" | grep -qE "(hostname|SNI|Host:)"; then
        local host
        host=$(echo "$line" | sed -nE 's/.*(hostname|SNI|Host:)[: ]*([^ ]+).*/\2/p' | head -1)
        echo -e "${BLUE}[$(ts)] [TARGET]${NC} ${GREEN}${host}${NC}"
    elif echo "$line" | grep -qiE "(error|fail|fatal)"; then
        log_error "nfqws2: $line"
    elif [[ "${LOG_LEVEL}" == "debug" ]]; then
        echo -e "${CYAN}[$(ts)] [NFQWS]${NC} $line"
    fi
}

process_dante_log() {
    local line="$1"
    if echo "$line" | grep -q "pass(1)"; then
        local dst
        dst=$(echo "$line" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+:[0-9]+' | tail -1)
        log_info "SOCKS5 → $dst"
    elif echo "$line" | grep -qiE "(error|fail|fatal)"; then
        log_error "sockd: $line"
    elif [[ "${LOG_LEVEL}" == "debug" ]]; then
        echo -e "${CYAN}[$(ts)] [DANTE]${NC} $line"
    fi
}

# ── Запуск nfqws2 ──────────────────────────────────────────────────────────────
start_nfqws() {
    (
        /usr/local/bin/nfqws2 "${NFQWS_ARGS[@]}" 2>&1 | \
        while IFS= read -r line; do
            process_nfqws_log "$line"
        done
    ) &
    NFQWS_PID=$!
    log_info "nfqws2 started (PID $NFQWS_PID)"
}

# ── Запуск Dante ───────────────────────────────────────────────────────────────
start_sockd() {
    (
        sockd -f /etc/sockd.conf -D 2>&1 | \
        while IFS= read -r line; do
            process_dante_log "$line"
        done
    ) &
    SOCKS_PID=$!
    log_info "sockd started (PID $SOCKS_PID)"
}

# ── Watchdog ───────────────────────────────────────────────────────────────────
watchdog() {
    while true; do
        sleep 5

        if ! kill -0 "$NFQWS_PID" 2>/dev/null; then
            log_warn "nfqws2 (PID $NFQWS_PID) died — restarting"
            start_nfqws
        fi

        if ! kill -0 "$SOCKS_PID" 2>/dev/null; then
            log_warn "sockd (PID $SOCKS_PID) died — restarting"
            start_sockd
        fi
    done
}

# ── Graceful shutdown ──────────────────────────────────────────────────────────
cleanup() {
    log_warn "Shutting down..."
    kill "$NFQWS_PID" "$SOCKS_PID" 2>/dev/null || true
    iptables -t mangle -F OUTPUT 2>/dev/null || true
    exit 0
}
trap cleanup SIGTERM SIGINT

# ══════════════════════════════════════════════════════════════════════════════
# MAIN
# ══════════════════════════════════════════════════════════════════════════════

log_info "=== zapret2 container starting ==="
log_info "SOCKS5 port : $SOCKS5_PORT"
log_info "NFQUEUE num : $NFQUEUE_NUM"
log_info "Log level   : $LOG_LEVEL"

check_caps
ensure_proxyuser
setup_iptables
write_sockd_conf
build_nfqws_args

start_nfqws

# Дать nfqws2 время подняться и захватить очередь
sleep 1

start_sockd

log_info "✓ Ready — SOCKS5 proxy on port $SOCKS5_PORT"

watchdog